services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - './:/var/www'
        networks:
            - bruxy_network
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - bruxy_network

    mysql:
        image: 'mysql:8.1.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'dbdata:/var/lib/mysql'
        networks:
            - bruxy_network

networks:
    bruxy_network:
        driver: bridge

volumes:
    dbdata:
        name: bruxy_dbdata